[package]
name = "citymodel-geometry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
citymodel-core = { path = "../citymodel-core" }
citymodel-coordinate = { path = "../citymodel-coordinate" }

[lints]
workspace = true
