[package]
name = "citymodel-gltf"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
citymodel-core = { path = "../citymodel-core" }
citymodel-geometry = { path = "../citymodel-geometry" }
citymodel-coordinate = { path = "../citymodel-coordinate" }
sha2 = "0.11"

[lints]
workspace = true
